# archtrace — zero runtime dependencies by design.
#
# `gate`, `test` and `coverage` run with nothing installed. `lint` and `types`
# need the dev extras (`pip install -e ".[dev]"`) and degrade to a clear skip
# rather than a confusing failure when they are absent.

ROOT ?= example
EVIDENCE_ROOT ?= $(ROOT)/_evidence_root
PY ?= python3
ARCHTRACE = ./archtrace --root $(ROOT) --evidence-root $(EVIDENCE_ROOT)
AGENT_DIR ?= .github/agents

# Every engagement in the repository, DISCOVERED rather than listed: an
# engagement is any directory holding a model/model.json. Listing them by hand
# is how `engagements/archtrace-self` sat in the tree with renders generated by
# renderer 1.1.0 while the renderer had moved to 1.2.0 -- CI only ever gated
# ROOT, which defaults to `example`, so nothing looked at it.
ENGAGEMENT_GLOBS ?= example engagements/*
ENGAGEMENTS = $(patsubst %/model/model.json,%,\
                $(wildcard $(addsuffix /model/model.json,$(ENGAGEMENT_GLOBS))))

.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "Deterministic, no dependencies:"
	@echo "  make check      the gates, against the bytes as committed"
	@echo "  make render     regenerate build outputs"
	@echo "  make gate       fmt + render + check (the pre-publish loop)"
	@echo "  make freshness  every engagement's renders match the renderer"
	@echo "  make engagements  list the engagements discovered in this repo"
	@echo "  make fmt        canonicalise JSON, refresh derived fields"
	@echo "  make report     grounding mix and NFR coverage"
	@echo "  make baseline   SPEC 9a — run this BEFORE anything else"
	@echo "  make agents     deterministic validation of agent definitions"
	@echo "  make config     print the thresholds this build enforces"
	@echo "  make test       full test suite"
	@echo "  make coverage   test suite under the stdlib tracer + floors"
	@echo ""
	@echo "Needs dev extras (pip install -e \".[dev]\"):"
	@echo "  make lint       ruff"
	@echo "  make types      mypy"
	@echo "  make secrets    gitleaks (also needs the gitleaks binary)"
	@echo ""
	@echo "  make pre-pr     everything above, in the order CI runs it"
	@echo "  make mine       run a code miner (needs REPO= and URI=); NOT in gate"
	@echo ""
	@echo "Override the engagement with ROOT=engagements/<name>"

# --- deterministic, dependency-free ----------------------------------------

.PHONY: check render fmt report baseline agents config gate test coverage \
        freshness engagements
check:    ; @$(ARCHTRACE) check
render:   ; @$(ARCHTRACE) render
fmt:      ; @$(ARCHTRACE) fmt
report:   ; @$(ARCHTRACE) report
baseline: ; @$(ARCHTRACE) baseline
config:   ; @$(ARCHTRACE) config
agents:   ; @./archtrace agents --directory "$(AGENT_DIR)"
gate: fmt render check

engagements:
	@for e in $(ENGAGEMENTS); do echo "$$e"; done

# Are the renders committed in EVERY engagement what the current renderer
# produces? This is the half of G6 that `make gate` cannot answer about itself:
# `gate` is `fmt render check`, so it regenerates the artifact before checking
# it and a hand edit is overwritten rather than reported. Re-rendering and then
# asking git whether anything moved catches both a hand edit and a stale commit,
# and it needs no evidence content -- so it works on engagements whose evidence
# lives outside the repository.
freshness:
	@# Refuse to judge a tree that is already modified. This target RE-RENDERS,
	@# which overwrites an uncommitted hand edit before the diff can see it --
	@# the same trap `make gate` falls into. Rendering over a dirty tree would
	@# therefore report "fresh" on an edit it had just destroyed. An uncommitted
	@# edit is `make check`'s job; this target answers the other question,
	@# whether the COMMITTED bytes are what the renderer produces.
	@git diff --quiet HEAD -- $(ENGAGEMENTS) || { \
	  echo "engagement files are already modified, so re-rendering would"; \
	  echo "overwrite them and this check would be meaningless."; \
	  echo "Commit or stash them first, then re-run. To gate an uncommitted"; \
	  echo "edit instead, run 'make check'."; \
	  git --no-pager diff --stat HEAD -- $(ENGAGEMENTS); \
	  exit 1; }
	@for e in $(ENGAGEMENTS); do \
	  ./archtrace --root "$$e" render >/dev/null || exit 1; \
	done
	@# `diff HEAD`, not bare `diff`: a bare diff compares against the index, so
	@# a stale render that was `git add`ed would pass. The question is whether
	@# the COMMITTED bytes are what the renderer produces.
	@git diff --quiet HEAD -- $(ENGAGEMENTS) || { \
	  echo "stale or hand-edited renders -- the committed bytes are not what"; \
	  echo "the renderer produces. Re-run 'make freshness' and commit:"; \
	  git --no-pager diff --stat HEAD -- $(ENGAGEMENTS); \
	  exit 1; }
	@echo "renders are fresh in: $(ENGAGEMENTS)"
test:
	@$(PY) -m unittest discover -s tools/tests -t tools
coverage:
	@$(PY) tools/coverage_gate.py

# --- developer tooling, optional -------------------------------------------
#
# These use `if/then/else`, NOT `cmd && tool || echo`. In shell, `||` fires when
# ANYTHING on its left fails -- the tool being absent, or the tool running and
# reporting violations -- and the `echo` then exits 0. That idiom made these
# three recipes incapable of failing: `make lint` printed real ruff errors,
# then printed "SKIP lint: ruff not installed", then exited 0. Three of the
# seven pre-pr gates were reporting green on findings they had just printed.
#
# A gate that cannot go red is not a gate. `test_infrastructure.py` now asserts
# both halves of this: a violation must fail, and an absent tool must skip.

.PHONY: lint types secrets
lint:
	@if command -v ruff >/dev/null 2>&1; then \
	  ruff check tools docs; \
	else \
	  echo "SKIP lint: ruff not installed (pip install -e \".[dev]\")"; \
	fi
types:
	@if command -v mypy >/dev/null 2>&1; then \
	  mypy; \
	else \
	  echo "SKIP types: mypy not installed (pip install -e \".[dev]\")"; \
	fi
secrets:
	@if command -v gitleaks >/dev/null 2>&1; then \
	  gitleaks detect --config .gitleaks.toml --redact --no-banner; \
	else \
	  echo "SKIP secrets: gitleaks not installed"; \
	fi

# --- the pre-PR gate --------------------------------------------------------
# Ordered cheapest-first so a trivial failure does not wait behind the suite.

.PHONY: pre-pr
pre-pr:
	@echo "== 1/9 lint ==";        $(MAKE) --no-print-directory lint
	@echo "== 2/9 types ==";       $(MAKE) --no-print-directory types
	@echo "== 3/9 secrets ==";     $(MAKE) --no-print-directory secrets
	@echo "== 4/9 agents ==";      $(MAKE) --no-print-directory agents
	@echo "== 5/9 tests ==";       $(MAKE) --no-print-directory test
	@echo "== 6/9 coverage ==";    $(MAKE) --no-print-directory coverage
	@# `check` before `gate`: `gate` regenerates the renders, so it cannot
	@# report a hand edit. This is the step that can.
	@echo "== 7/9 check ==";       $(MAKE) --no-print-directory check
	@echo "== 8/9 freshness ==";   $(MAKE) --no-print-directory freshness
	@echo "== 9/9 gate ==";        $(MAKE) --no-print-directory gate
	@echo ""
	@echo "pre-pr passed. 'Green' means grounded and internally consistent."
	@echo "It never means correct."

# --- mining (third-party toolchain; deliberately outside the gate) ----------

REPO ?=
ID ?=
URI ?=
CLASS ?= internal
# No default: `archtrace mine` makes --retention-until required=True
# specifically so a retention date is a conscious choice, never a default
# nobody chose. RETAIN ?= 2029-01-01 here used to silently satisfy that flag
# on every `make mine` call -- the CLI's own required-argument check could
# never fire through this entry point. See docs/code-quality-plan.md §12.8.
RETAIN ?=
.PHONY: mine mine-dry
mine mine-dry:
	@test -n "$(REPO)" || { echo "set REPO=/path/to/repository"; exit 2; }
	@test -n "$(URI)"  || { echo "set URI=<repository URL for the record>"; exit 2; }
	@test -n "$(RETAIN)" || { echo "set RETAIN=<retention date, e.g. 2029-01-01>"; exit 2; }
	@$(ARCHTRACE) mine --repo "$(REPO)" $(if $(ID),--id "$(ID)",) \
	  --source-uri "$(URI)" --date "$$(date -u +%Y-%m-%d)" \
	  --classification "$(CLASS)" --retention-until "$(RETAIN)" \
	  $(if $(filter mine-dry,$(MAKECMDGOALS)),--dry-run,)
