# archtrace — zero runtime dependencies by design.
#
# `gate`, `test` and `coverage` run with nothing installed. `lint` and `types`
# need the dev extras (`pip install -e ".[dev]"`) and degrade to a clear skip
# rather than a confusing failure when they are absent.

ROOT ?= example
EVIDENCE_ROOT ?= $(ROOT)/_evidence_root
PY ?= python3
# ARCHTRACE_PYTHON threads PY through the shim, which otherwise hardcodes
# python3 -- so `make gate PY=python3.9` really does run on 3.9.
ARCHTRACE = ARCHTRACE_PYTHON=$(PY) ./archtrace --root $(ROOT) --evidence-root $(EVIDENCE_ROOT)
AGENT_DIR ?= .github/agents

# Every engagement in the repository, DISCOVERED rather than listed: an
# engagement is any directory matching one of ENGAGEMENT_GLOBS that holds a
# model/model.json. Listing them by hand is how `engagements/archtrace-self`
# sat in the tree with renders generated by renderer 1.1.0 while the renderer
# had moved to 1.2.0 -- CI only ever gated ROOT, which defaults to `example`.
#
# Glob-driven, not recursive: `$(wildcard)` does not descend, so the default
# covers `engagements/<name>` and one level below it for repositories that
# group by client or team. Deeper than that, or somewhere else entirely, set
# ENGAGEMENT_GLOBS. `make engagements` prints what was actually found, which is
# the check that the globs match what you think they do.
ENGAGEMENT_GLOBS ?= example engagements/* engagements/*/*
ENGAGEMENTS = $(sort $(patsubst %/model/model.json,%,\
                $(wildcard $(addsuffix /model/model.json,$(ENGAGEMENT_GLOBS)))))

# Where the evidence CONTENT lives, when it is not beside the engagement.
# Empty by default, which leaves each engagement on the CLI's own
# `<root>/_evidence_root`. See the note on `freshness` for why this matters
# there: G6 re-renders, and some render columns are derived from evidence.
FRESHNESS_EVIDENCE_ROOT ?=

.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "Deterministic, no dependencies:"
	@echo "  make check      the gates, against the bytes as committed"
	@echo "  make render     regenerate build outputs"
	@echo "  make gate       fmt + render + check (the pre-publish loop)"
	@echo "  make freshness  every engagement's renders match the renderer"
	@echo "  make engagements  list the engagements discovered in this repo"
	@echo "  make evidence-guard  no recording content is committed"
	@echo "  make fmt        canonicalise JSON, refresh derived fields"
	@echo "  make report     grounding mix and NFR coverage"
	@echo "  make baseline   SPEC 9a — run this BEFORE anything else"
	@echo "  make agents     deterministic validation of agent definitions"
	@echo "  make config     print the thresholds this build enforces"
	@echo "  make test       full test suite"
	@echo "  make coverage   test suite under the stdlib tracer + floors"
	@echo ""
	@echo "Needs dev extras (pip install -e \".[dev]\"):"
	@echo "  make lint       ruff"
	@echo "  make types      mypy"
	@echo "  make secrets    gitleaks (also needs the gitleaks binary)"
	@echo ""
	@echo "  make pre-pr     everything above, in the order CI runs it"
	@echo "  make mine       run a code miner (needs REPO= and URI=); NOT in gate"
	@echo ""
	@echo "Override the engagement with ROOT=engagements/<name>"

# --- deterministic, dependency-free ----------------------------------------

.PHONY: check render fmt report baseline agents config gate test coverage \
        freshness engagements evidence-guard
check:    ; @$(ARCHTRACE) check
render:   ; @$(ARCHTRACE) render
fmt:      ; @$(ARCHTRACE) fmt
report:   ; @$(ARCHTRACE) report
baseline: ; @$(ARCHTRACE) baseline
config:   ; @$(ARCHTRACE) config
agents:   ; @ARCHTRACE_PYTHON=$(PY) ./archtrace agents --directory "$(AGENT_DIR)"
gate: fmt render check

engagements:
	@for e in $(ENGAGEMENTS); do echo "$$e"; done

# Recording content must never enter git (SPEC 0.4): a repository cannot
# satisfy a retention obligation, and deleting a file does not delete the blob.
#
# There was a pre-commit hook for this and nothing else. It checks the STAGED
# diff, and it only runs on a machine where somebody ran `pre-commit install` --
# so the most important control in the tree ran on the honour system, and a
# single `--no-verify` or a fresh clone bypassed it permanently. This asks the
# same question of what is actually COMMITTED, needs nothing installed, and so
# runs in the same CI job as the gate.
#
# `example/_evidence_root/` is the one deliberate exception, documented in
# .gitignore: the worked example's evidence is synthetic, and shipping it is
# what lets the example gate itself in CI.
EVIDENCE_EXCEPTION ?= example/_evidence_root/
evidence-guard:
	@# Prove we CAN check before reporting that we did. The first version of
	@# this recipe piped `git ls-files` through `|| true`, so outside a git
	@# repository the command failed, the failure was swallowed, and the target
	@# printed "no recording content is committed" and exited 0 -- a guard that
	@# passes when it cannot look, which is the exact false green it was added
	@# to close.
	@git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { \
	  echo "not a git repository, so nothing can be said about what is"; \
	  echo "committed. Refusing to report a pass for a check that did not run."; \
	  exit 1; }
	@bad=$$(git ls-files -- '*_evidence_root/*' \
	          | grep -v '^$(EVIDENCE_EXCEPTION)' || true); \
	 test -z "$$bad" || { \
	   echo "recording content is committed:"; \
	   echo "$$bad" | sed 's/^/  /'; \
	   echo ""; \
	   echo "a repository cannot satisfy a retention obligation, and deleting"; \
	   echo "a file does not delete the blob. Remove it from history, not just"; \
	   echo "from the tree."; \
	   exit 1; }
	@echo "no recording content is committed (exception: $(EVIDENCE_EXCEPTION))"

# Are the renders committed in EVERY engagement what the current renderer
# produces? `make check` answers this for ROOT only, which defaults to
# `example`; that is how `engagements/archtrace-self` sat in the tree carrying
# renders from an older renderer with nothing looking at it. This asks G6, and
# only G6, of each engagement found, which keeps G1 and G2 from drowning the
# result on an engagement whose evidence content is elsewhere.
#
# That does NOT make it independent of evidence, and an earlier version of this
# comment wrongly claimed it did. G6 re-renders in memory to compare, and some
# columns of traceability.md and traceability.csv are derived from evidence
# content -- source locators, symbol and relation counts. An engagement whose
# evidence lives in the system of record rather than beside the model is
# therefore reported STALE here, correctly but unhelpfully: the renderer cannot
# reproduce what it cannot read. Point FRESHNESS_EVIDENCE_ROOT at that content,
# or keep such engagements out of ENGAGEMENT_GLOBS and gate them where their
# evidence is reachable. `example` ships its evidence; `engagements/archtrace-self`
# cites none whose content reaches a render.
freshness:
	@# Discovery finding nothing must be an error, not a pass. A rename of
	@# engagements/, a bad ENGAGEMENT_GLOBS or an unexpected checkout layout
	@# would otherwise make this target succeed while gating nothing -- a gate
	@# incapable of failing, which is the defect this target exists to close.
	@test -n "$(strip $(ENGAGEMENTS))" || { \
	  echo "no engagements found under: $(ENGAGEMENT_GLOBS)"; \
	  echo "an engagement is a directory containing model/model.json."; \
	  echo "nothing was checked, so this is a failure, not a pass."; \
	  exit 1; }
	@# Make splits variables on whitespace, so a path containing a space would
	@# silently become two engagements: `git diff` would match neither, the
	@# check would pass, and `render` would write junk directories. Refusing is
	@# honest; pretending to have checked is the failure mode this target is
	@# about. (Quoting "$$e" in the loop does not help -- the split happens when
	@# Make expands $(ENGAGEMENTS) into the recipe, before the shell sees it.)
	@for e in $(ENGAGEMENTS); do \
	  test -d "$$e" || { \
	    echo "engagement path is not a directory: '$$e'"; \
	    echo "paths containing spaces are not supported here; rename it."; \
	    exit 1; }; \
	done
	@# Non-mutating, deliberately. An earlier version re-rendered onto disk and
	@# diffed afterwards, which (a) reproduced the `make gate` defect this
	@# target exists to close, by overwriting an uncommitted hand edit before
	@# the diff could see it, and (b) on any machine where the evidence content
	@# lives outside the repository -- the documented normal -- rewrote three
	@# committed deliverables with degraded placeholder versions and left them
	@# there. G6 already answers this question against the committed bytes
	@# without touching them, so ask G6.
	@ev=; test -z "$(FRESHNESS_EVIDENCE_ROOT)" \
	  || ev="--evidence-root $(FRESHNESS_EVIDENCE_ROOT)"; \
	failed=; for e in $(ENGAGEMENTS); do \
	  ARCHTRACE_PYTHON=$(PY) ./archtrace --root "$$e" $$ev check --only G6 \
	      >/dev/null 2>&1 \
	    || { echo "STALE  $$e"; ARCHTRACE_PYTHON=$(PY) ./archtrace --root "$$e" \
	           $$ev check --only G6 \
	           2>&1 | sed -n 's/^BLOCK/  BLOCK/p;s/^        /      /p'; \
	         failed=1; }; \
	done; \
	test -z "$$failed" || { \
	  echo ""; \
	  echo "committed renders are not what the renderer produces."; \
	  echo "run 'make render ROOT=<engagement>' for each and commit."; \
	  exit 1; }
	@echo "renders are fresh in: $(ENGAGEMENTS)"
test:
	@$(PY) -m unittest discover -s tools/tests -t tools
coverage:
	@$(PY) tools/coverage_gate.py

# --- developer tooling, optional -------------------------------------------
#
# These use `if/then/else`, NOT `cmd && tool || echo`. In shell, `||` fires when
# ANYTHING on its left fails -- the tool being absent, or the tool running and
# reporting violations -- and the `echo` then exits 0. That idiom made these
# three recipes incapable of failing: `make lint` printed real ruff errors,
# then printed "SKIP lint: ruff not installed", then exited 0. Three of the
# seven pre-pr gates were reporting green on findings they had just printed.
#
# A gate that cannot go red is not a gate. `test_infrastructure.py` now asserts
# both halves of this: a violation must fail, and an absent tool must skip.

.PHONY: lint types secrets
lint:
	@if command -v ruff >/dev/null 2>&1; then \
	  ruff check tools docs; \
	else \
	  echo "SKIP lint: ruff not installed (pip install -e \".[dev]\")"; \
	fi
types:
	@if command -v mypy >/dev/null 2>&1; then \
	  mypy; \
	else \
	  echo "SKIP types: mypy not installed (pip install -e \".[dev]\")"; \
	fi
secrets:
	@if command -v gitleaks >/dev/null 2>&1; then \
	  gitleaks detect --config .gitleaks.toml --redact --no-banner; \
	else \
	  echo "SKIP secrets: gitleaks not installed"; \
	fi

# --- the pre-PR gate --------------------------------------------------------
# Ordered cheapest-first so a trivial failure does not wait behind the suite.

.PHONY: pre-pr
pre-pr:
	@echo "== 1/10 lint ==";          $(MAKE) --no-print-directory lint
	@echo "== 2/10 types ==";         $(MAKE) --no-print-directory types
	@echo "== 3/10 secrets ==";       $(MAKE) --no-print-directory secrets
	@echo "== 4/10 agents ==";        $(MAKE) --no-print-directory agents
	@echo "== 5/10 evidence ==";      $(MAKE) --no-print-directory evidence-guard
	@echo "== 6/10 tests ==";         $(MAKE) --no-print-directory test
	@echo "== 7/10 coverage ==";      $(MAKE) --no-print-directory coverage
	@# `check` before `gate`: `gate` regenerates the renders, so it cannot
	@# report a hand edit. This is the step that can.
	@echo "== 8/10 check ==";         $(MAKE) --no-print-directory check
	@echo "== 9/10 freshness ==";     $(MAKE) --no-print-directory freshness
	@echo "== 10/10 gate ==";          $(MAKE) --no-print-directory gate
	@echo ""
	@echo "pre-pr passed. 'Green' means grounded and internally consistent."
	@echo "It never means correct."

# --- mining (third-party toolchain; deliberately outside the gate) ----------

REPO ?=
ID ?=
URI ?=
CLASS ?= internal
# No default: `archtrace mine` makes --retention-until required=True
# specifically so a retention date is a conscious choice, never a default
# nobody chose. RETAIN ?= 2029-01-01 here used to silently satisfy that flag
# on every `make mine` call -- the CLI's own required-argument check could
# never fire through this entry point. See docs/code-quality-plan.md §12.8.
RETAIN ?=
.PHONY: mine mine-dry
mine mine-dry:
	@test -n "$(REPO)" || { echo "set REPO=/path/to/repository"; exit 2; }
	@test -n "$(URI)"  || { echo "set URI=<repository URL for the record>"; exit 2; }
	@test -n "$(RETAIN)" || { echo "set RETAIN=<retention date, e.g. 2029-01-01>"; exit 2; }
	@$(ARCHTRACE) mine --repo "$(REPO)" $(if $(ID),--id "$(ID)",) \
	  --source-uri "$(URI)" --date "$$(date -u +%Y-%m-%d)" \
	  --classification "$(CLASS)" --retention-until "$(RETAIN)" \
	  $(if $(filter mine-dry,$(MAKECMDGOALS)),--dry-run,)
